# Generated by Django 5.1.1 on 2024-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restoranlar", "0002_menu_alter_restoran_malumotlari_tel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.ImageField(upload_to="menus/"),
        ),
    ]
