# Generated by Django 5.1.1 on 2024-11-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mehmonhonalar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mehmonhonlar",
            name="jop_time",
            field=models.CharField(max_length=50),
        ),
    ]
