# Generated by Django 5.1.1 on 2024-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mehmonhonalar", "0002_alter_mehmonhonlar_jop_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mehmonhonlar",
            name="image",
            field=models.ImageField(default=1, upload_to="hotels/"),
            preserve_default=False,
        ),
    ]
