# Generated by Django 5.1.1 on 2024-11-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mehmonhonalar", "0003_alter_mehmonhonlar_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mehmonhonlar",
            name="tier",
            field=models.CharField(
                choices=[
                    ("Gold", "Gold"),
                    ("Silver", "Silver"),
                    ("Standard", "Standard"),
                ],
                default="Standard",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mehmonhonlar",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hotels/"),
        ),
        migrations.AlterField(
            model_name="mehmonhonlar",
            name="jop_time",
            field=models.DateTimeField(),
        ),
    ]
