# Generated by Django 5.1.1 on 2024-11-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mehmonhonalar", "0004_mehmonhonlar_tier_alter_mehmonhonlar_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mehmonhonlar",
            name="jop_time",
            field=models.CharField(max_length=50),
        ),
    ]
