# Generated by Django 5.1.1 on 2024-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mehmonhonalar", "0005_alter_mehmonhonlar_jop_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mehmonhonlar",
            old_name="jop_time",
            new_name="job_time",
        ),
        migrations.RemoveField(
            model_name="mehmonhonlar",
            name="tier",
        ),
        migrations.AddField(
            model_name="mehmonhonlar",
            name="star_rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
